name: 'Mind Your Drone Business!'
favicon: null
layout_spectrum: 0.1953191130887717
typography_spectrum: 0.6232514239381999
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.16539749898947775
  lightness: 0.1534315946046263
  saturation: 0.3365570451132953
  rhythmicContrast: 0.9999741159845144
purpose: []
